{{ if not .Values.configmap }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup.name" . }}-config
data:
  backup.yaml: |
{{ if .Values.config }}
{{ toYaml .Values.config | indent 4 }}
{{ else }}
    keep:
      last: 5
      daily: 7
      weekly: 4
{{ end }}
{{ end }}
